package com.example.demo.dto

data class ClientDto(
    var login: String,
    var firstname: String,
    var lastname: String,
    var role: String,
    var description: String,
    var InitialDuMilieu: String,
    var genre: String,
    var pays: String,
    var adresse: String,
    var adresseMail: String,
    var dateNaissance: String,
    var age: String,
    var CCType: String,
    var CCNumber: String,
    var CVV2: String,
    var CCExpires: String,
    var Occupation: String,
    var Company: String,
    var AnneeV: String?,
    var ModeleV: String?,
    var MarqueV: String?,
    var Pounds: String,
    var Kilograms: String,
    var FeetInches: String,
    var Centimeters: String,
    var Latitude: String,
    var Longitude: String,
    var password: String,
    var estValide: Boolean,
    val id: Long? = null)
